### ISSUE TITLE
http cals brake https sites

### ISSUE THREAD

**Issue by digitalfredy** [ikks/moinmoin-github-osm#1]
Hi Igor, 

My advice is to use https as default and leave an option to force http

![screen shot 2017-03-15 at 7 57 44](https://cloud.githubusercontent.com/assets/1372919/23947561/9ea15258-0955-11e7-9504-a7f732c77455.png)

Thanks for your work :)

**Comment by digitalfredy** [comment]
URL : https://flisol.info/IgorTamara/Pruebas

**Comment by ikks** [comment]
I changed a little bit the map.js script, but it depends on openstreetmap website itself, I sent a pr for this, if  in two days they haven't merged and deployed, I can work on a workaround.

https://github.com/openstreetmap/openstreetmap-website/pull/1489

**Comment by ikks** [comment]
I don't know how long can it take for OSM to accept the pr, I applied the workaround, good to go.
